#                                                          #
# Start of a minicloud-master deployment                   #
#                                                          #
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: minicloud-rx-master
  name: minicloud-rx-master
spec:
  replicas: 1
  selector:
    matchLabels:
      run: minicloud-rx-master
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: minicloud-rx-master
    spec:
      containers:
      - image: gcr.io/minicloud-rx/minicloud-rx-master
        name: minicloud-rx-master
        ports:
        - containerPort: 8080
        resources: {}
status: {}
#                                                          #
# End of a minicloud-master deployment                     #
#                                                          #