#                                                          #
# Start of a headless worker service to create DNS records #
#                                                          #
apiVersion: v1
kind: Service
metadata:
  name: minicloud-rx-worker
  labels:
    app: minicloud-rx-worker
spec:
  ports:
  - port: 8080
    name: web
  clusterIP: None
  selector:
    app: minicloud-rx-worker
#                                                          #
# End of A headless worker service to create DNS records   #
#                                                          #